services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/terraform/setup
      - ./deploy:/terraform/deploy
    working_dir: /terraform
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=eu-west-3
      - TF_WORKSPACE=${TF_WORKSPACE}
      - TF_VAR_db_password=${TF_VAR_DB_PASSWORD}
      - TF_VAR_django_secret_key=${TF_VAR_DJANGO_SECRET_KEY}
      - TF_VAR_ecr_proxy_image=${TF_VAR_ECR_REPO_PROXY}
      - TF_VAR_ecr_app_image=${TF_VAR_ECR_REPO_APP}