

name: checks

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test-lint:
          name: test and lint
          uses: ./.github/workflows/test-and-lint.yml
          secrets:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

