name: destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: which environmenet to remove aws resources for?
        options:
          - staging
          - prod

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          export TF_WORKSACE=${{github.event.inputs.environment}}
          cd terraform/
          docker compose run --rm terraform -chdir=deploy/ init
          docker compose run --rm terraform -chdir=deploy destroy -auto-approve

