name: test-and-lint
on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: "USER name for docker hub"
      DOCKERHUB_TOKEN:
        required: true
        description: "Token for docker hub AUTH"

jobs:
  python:
    name: python
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: flake8
        run: docker compose run --rm app sh -c "flake8"
